---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: configure-server.yml
  when: glusterfs_volumes

- include_tasks: configure-client.yml
  when: glusterfs_mounts